version: "3.4"

services:
  app:
    image: registry.gitlab.com/zulufun/learning-docker:v1 
    ports:
      - "${PUBLIC_PORT}:${PORT}"
    restart: unless-stopped
    environment:
      PORT: ${PORT}
