version: "3.7"

services:
  app:
    image: learning-docker/vue:v1
    volumes:
      - ./src:/app/src
    ports:
      - "5000:8080"
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 2g   # Giới hạn RAM là 2GB
          cpus: "1"  # Giới hạn CPU là 1 cores
